services:
  Happyr\WordpressBundle\Api\WpClient:
    arguments: ['@Psr\Http\Client\ClientInterface', '@Psr\Http\Message\RequestFactoryInterface', '%happyr_wordpress.remote_url%']

  Happyr\WordpressBundle\Parser\MessageParser:
    arguments: ['@event_dispatcher']

  Happyr\WordpressBundle\Service\Wordpress:
    arguments: ['@Happyr\WordpressBundle\Api\WpClient', '@Happyr\WordpressBundle\Parser\MessageParser',  ~, ~]

  Happyr\WordpressBundle\Twig\WordpressExtension:
    arguments: ['@Happyr\WordpressBundle\Service\Wordpress']

  Happyr\WordpressBundle\Parser\RewriteLinks:
    arguments: ['%happyr_wordpress.remote_url%', '@router']
    tags: ['kernel.event_subscriber']
